using System.Security.Cryptography;
using Cauce.Application.Common.Interfaces;
using Cauce.Application.Common.Interfaces.Identity;
using Cauce.Domain.Identity;
using MediatR;
using Microsoft.Extensions.Logging;

namespace Cauce.Application.Identity.UseCases.GenerateInvitationCode;

/// <summary>
/// Handler de la generación de códigos de invitación. Verifica que el solicitante
/// sea un nutricionista existente, genera un código alfanumérico sin caracteres
/// ambiguos y lo persiste con vigencia de 72 horas.
/// </summary>
public sealed class GenerateInvitationCodeCommandHandler
    : IRequestHandler<GenerateInvitationCodeCommand, GenerateInvitationCodeResult>
{
    private const string CodeAlphabet = "ABCDEFGHJKMNPQRSTUVWXYZ23456789";
    private const int CodeLength = 10;
    private const int MaxGenerationAttempts = 3;

    private readonly IUserRepository _userRepository;
    private readonly IInvitationCodeRepository _invitationCodeRepository;
    private readonly IUnitOfWork _unitOfWork;
    private readonly ILogger<GenerateInvitationCodeCommandHandler> _logger;

    /// <summary>
    /// Inicializa el handler con sus dependencias.
    /// </summary>
    public GenerateInvitationCodeCommandHandler(
        IUserRepository userRepository,
        IInvitationCodeRepository invitationCodeRepository,
        IUnitOfWork unitOfWork,
        ILogger<GenerateInvitationCodeCommandHandler> logger)
    {
        _userRepository = userRepository;
        _invitationCodeRepository = invitationCodeRepository;
        _unitOfWork = unitOfWork;
        _logger = logger;
    }

    /// <inheritdoc />
    public async Task<GenerateInvitationCodeResult> Handle(
        GenerateInvitationCodeCommand request,
        CancellationToken cancellationToken)
    {
        var user = await _userRepository
            .FindByKeycloakIdAsync(request.NutritionistUserId.ToString(), cancellationToken)
            .ConfigureAwait(false);

        var nutritionistRoleId = await _userRepository
            .GetRoleIdAsync(UserRoles.Nutritionist, cancellationToken)
            .ConfigureAwait(false);

        if (user is null || user.RoleId != nutritionistRoleId)
        {
            throw new UnauthorizedAccessException("Solo un nutricionista puede generar códigos de invitación.");
        }

        var utcNow = DateTime.UtcNow;
        var code = await GenerateUniqueCodeAsync(cancellationToken).ConfigureAwait(false);

        var invitation = InvitationCode.Generate(Guid.NewGuid(), code, user.Id, utcNow, InvitationCode.Validity);
        await _invitationCodeRepository.AddAsync(invitation, cancellationToken).ConfigureAwait(false);

        // La auditoría (Register / invitation_codes, tabla sin trigger) la enrola el AuditingBehavior
        // antes de este handler; este SaveChanges la persiste de forma atómica (DEC-B5-01, acta A8).
        await _unitOfWork.SaveChangesAsync(cancellationToken).ConfigureAwait(false);

        _logger.LogInformation("Invitation code {CodeId} generated by nutritionist {UserId}.", invitation.Id, user.Id);

        return new GenerateInvitationCodeResult(invitation.Code, invitation.ExpiresAt);
    }

    private async Task<string> GenerateUniqueCodeAsync(CancellationToken ct)
    {
        for (var attempt = 0; attempt < MaxGenerationAttempts; attempt++)
        {
            var candidate = new string(RandomNumberGenerator.GetItems<char>(CodeAlphabet.AsSpan(), CodeLength));
            var existing = await _invitationCodeRepository.FindByCodeAsync(candidate, ct).ConfigureAwait(false);
            if (existing is null)
            {
                return candidate;
            }
        }

        throw new InvalidOperationException("No se pudo generar un código de invitación único.");
    }
}
