// <auto-generated />
using System;
using Cauce.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Cauce.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CauceDbContext))]
    [Migration("20260705182639_AddUserIsInActivePilot")]
    partial class AddUserIsInActivePilot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Cauce.Domain.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("audit_log_id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AdditionalContext")
                        .HasColumnType("jsonb")
                        .HasColumnName("additional_context");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("entity_type");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("NewValuesHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("new_values_hash");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("OldValuesHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("old_values_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("ActionType", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_logs_action_type_occurred_at");

                    b.HasIndex("ActorUserId", "OccurredAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_audit_logs_actor_user_id_occurred_at");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_audit_logs_entity_type_entity_id")
                        .HasFilter("entity_id IS NOT NULL");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Cauce.Domain.ClinicalRegistry.ClinicalNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("note_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("MealId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid?>("SymptomId")
                        .HasColumnType("uuid")
                        .HasColumnName("symptom_id");

                    b.HasKey("Id")
                        .HasName("pk_clinical_notes");

                    b.HasIndex("MealId")
                        .HasDatabaseName("ix_clinical_notes_meal_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_clinical_notes_patient_id");

                    b.HasIndex("SymptomId")
                        .HasDatabaseName("ix_clinical_notes_symptom_id");

                    b.ToTable("clinical_notes", null, t =>
                        {
                            t.HasCheckConstraint("ck_clinical_notes_content", "length(content) > 0");

                            t.HasCheckConstraint("ck_clinical_notes_xor", "(meal_id IS NULL) <> (symptom_id IS NULL)");
                        });
                });

            modelBuilder.Entity("Cauce.Domain.ClinicalRegistry.CustomFood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("custom_food_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<decimal>("PortionSizeGrams")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("portion_size_grams");

                    b.HasKey("Id")
                        .HasName("pk_custom_foods");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_custom_foods_patient");

                    b.HasIndex("PatientId", "Name")
                        .IsUnique()
                        .HasDatabaseName("uq_custom_food_per_patient");

                    b.ToTable("custom_foods", null, t =>
                        {
                            t.HasCheckConstraint("ck_custom_foods_portion", "portion_size_grams > 0");
                        });
                });

            modelBuilder.Entity("Cauce.Domain.ClinicalRegistry.CustomFoodIngredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ingredient_id");

                    b.Property<Guid>("CustomFoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("custom_food_id");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("food_id");

                    b.Property<decimal>("ProportionGrams")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("proportion_grams");

                    b.HasKey("Id")
                        .HasName("pk_custom_food_ingredients");

                    b.HasIndex("FoodId")
                        .HasDatabaseName("ix_custom_food_ingredients_food_id");

                    b.HasIndex("CustomFoodId", "FoodId")
                        .IsUnique()
                        .HasDatabaseName("uq_ingredient_per_custom_food");

                    b.ToTable("custom_food_ingredients", null, t =>
                        {
                            t.HasCheckConstraint("ck_custom_food_ingredients_proportion", "proportion_grams > 0");
                        });
                });

            modelBuilder.Entity("Cauce.Domain.ClinicalRegistry.FoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("food_id");

                    b.Property<decimal>("CaloriesPer100g")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("calories_per_100g");

                    b.Property<decimal>("CarbsGPer100g")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("carbs_g_per_100g");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("FatGPer100g")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("fat_g_per_100g");

                    b.Property<decimal>("FiberGPer100g")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("fiber_g_per_100g");

                    b.Property<string>("FodmapLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("fodmap_level");

                    b.Property<string>("FodmapTags")
                        .HasColumnType("text")
                        .HasColumnName("fodmap_tags");

                    b.Property<byte>("FructoseLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("fructose_level");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPeruvian")
                        .HasColumnType("boolean")
                        .HasColumnName("is_peruvian");

                    b.Property<byte>("LactoseLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("lactose_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<byte>("OligosLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("oligos_level");

                    b.Property<byte>("PolyolsLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0)
                        .HasColumnName("polyols_level");

                    b.Property<decimal>("ProteinGPer100g")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("protein_g_per_100g");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_food_items");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_food_items_category");

                    b.HasIndex("FodmapLevel")
                        .HasDatabaseName("ix_food_items_fodmap");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_food_items_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_food_items_name");

                    b.ToTable("food_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_food_items_calories", "calories_per_100g >= 0");

                            t.HasCheckConstraint("ck_food_items_carbs", "carbs_g_per_100g >= 0");

                            t.HasCheckConstraint("ck_food_items_fat", "fat_g_per_100g >= 0");

                            t.HasCheckConstraint("ck_food_items_fiber", "fiber_g_per_100g >= 0");

                            t.HasCheckConstraint("ck_food_items_fructose_level", "fructose_level BETWEEN 0 AND 2");

                            t.HasCheckConstraint("ck_food_items_lactose_level", "lactose_level BETWEEN 0 AND 2");

                            t.HasCheckConstraint("ck_food_items_oligos_level", "oligos_level BETWEEN 0 AND 2");

                            t.HasCheckConstraint("ck_food_items_polyols_level", "polyols_level BETWEEN 0 AND 2");

                            t.HasCheckConstraint("ck_food_items_protein", "protein_g_per_100g >= 0");
                        });
                });

            modelBuilder.Entity("Cauce.Domain.ClinicalRegistry.IbsSssAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<string>("AssessmentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("assessment_type");

                    b.Property<int>("BloatingSeverity")
                        .HasColumnType("integer")
                        .HasColumnName("bloating_severity");

                    b.Property<int>("BowelHabitsDissatisfaction")
                        .HasColumnType("integer")
                        .HasColumnName("bowel_habits_dissatisfaction");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<int>("CycleNumber")
                        .HasColumnType("integer")
                        .HasColumnName("cycle_number");

                    b.Property<int>("LifeInterference")
                        .HasColumnType("integer")
                        .HasColumnName("life_interference");

                    b.Property<DateOnly?>("NextAssessmentDate")
                        .HasColumnType("date")
                        .HasColumnName("next_assessment_date");

                    b.Property<int>("PainFrequency")
                        .HasColumnType("integer")
                        .HasColumnName("pain_frequency");

                    b.Property<int>("PainSeverity")
                        .HasColumnType("integer")
                        .HasColumnName("pain_severity");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("SeverityCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity_category");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.HasKey("Id")
                        .HasName("pk_ibs_sss_assessments");

                    b.HasIndex("SeverityCategory")
                        .HasDatabaseName("ix_ibs_sss_severity");

                    b.HasIndex("TotalScore")
                        .HasDatabaseName("ix_ibs_sss_total_score");

                    b.HasIndex(new[] { "PatientId" }, "ix_ibs_sss_patient_id")
                        .HasDatabaseName("ix_ibs_sss_assessments_patient_id");

                    b.HasIndex(new[] { "PatientId" }, "uq_ibs_sss_baseline_per_patient")
                        .IsUnique()
                        .HasDatabaseName("ix_ibs_sss_assessments_patient_id1")
                        .HasFilter("assessment_type = 'baseline'");

                    b.ToTable("ibs_sss_assessments", null, t =>
                        {
                            t.HasCheckConstraint("ck_ibs_sss_bloating_severity", "bloating_severity BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_ibs_sss_bowel_habits", "bowel_habits_dissatisfaction BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_ibs_sss_cycle_number", "cycle_number >= 0");

                            t.HasCheckConstraint("ck_ibs_sss_life_interference", "life_interference BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_ibs_sss_pain_frequency", "pain_frequency BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_ibs_sss_pain_severity", "pain_severity BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_ibs_sss_total_score", "total_score BETWEEN 0 AND 500");
                        });
                });

            modelBuilder.Entity("Cauce.Domain.ClinicalRegistry.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("meal_id");

                    b.Property<DateTime>("ClientCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("client_created_at");

                    b.Property<Guid>("ClientGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("client_guid");

                    b.Property<DateTime>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("MealTime")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("meal_time");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sync_status");

                    b.HasKey("Id")
                        .HasName("pk_meals");

                    b.HasIndex("ClientCreatedAt")
                        .HasDatabaseName("ix_meals_client_created_at");

                    b.HasIndex("ClientGuid")
                        .IsUnique()
                        .HasDatabaseName("ux_meals_client_guid");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_meals_patient_id");

                    b.HasIndex("PatientId", "ClientCreatedAt")
                        .HasDatabaseName("ix_meals_patient_clientcrat");

                    b.ToTable("meals", (string)null);
                });

            modelBuilder.Entity("Cauce.Domain.ClinicalRegistry.MealItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("meal_item_id");

                    b.Property<Guid?>("CustomFoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("custom_food_id");

                    b.Property<Guid?>("FoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("food_id");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid")
                        .HasColumnName("meal_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("quantity");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_meal_items");

                    b.HasIndex("CustomFoodId")
                        .HasDatabaseName("ix_meal_items_custom_food_id");

                    b.HasIndex("FoodId")
                        .HasDatabaseName("ix_meal_items_food_id");

                    b.HasIndex("MealId")
                        .HasDatabaseName("ix_meal_items_meal_id");

                    b.ToTable("meal_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_meal_items_food_xor", "(food_id IS NULL) <> (custom_food_id IS NULL)");

                            t.HasCheckConstraint("ck_meal_items_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Cauce.Domain.ClinicalRegistry.Symptom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("symptom_id");

                    b.Property<Guid?>("AssociatedMealId")
                        .HasColumnType("uuid")
                        .HasColumnName("associated_meal_id");

                    b.Property<DateTime>("ClientCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("client_created_at");

                    b.Property<Guid>("ClientGuid")
                        .HasColumnType("uuid")
                        .HasColumnName("client_guid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("HasMealAssociation")
                        .HasColumnType("boolean")
                        .HasColumnName("has_meal_association");

                    b.Property<int>("Intensity")
                        .HasColumnType("integer")
                        .HasColumnName("intensity");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("SymptomType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("symptom_type");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sync_status");

                    b.HasKey("Id")
                        .HasName("pk_symptoms");

                    b.HasIndex("AssociatedMealId")
                        .HasDatabaseName("ix_symptoms_associated_meal_id");

                    b.HasIndex("ClientCreatedAt")
                        .HasDatabaseName("ix_symptoms_client_created_at");

                    b.HasIndex("ClientGuid")
                        .IsUnique()
                        .HasDatabaseName("ux_symptoms_client_guid");

                    b.HasIndex("HasMealAssociation")
                        .HasDatabaseName("ix_symptoms_has_meal_association");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_symptoms_patient_id");

                    b.ToTable("symptoms", null, t =>
                        {
                            t.HasCheckConstraint("ck_symptoms_intensity", "intensity BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("Cauce.Domain.Identity.ConsentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("consent_id");

                    b.Property<DateTime>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("ConsentTextHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("consent_text_hash");

                    b.Property<string>("DocumentVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("document_version");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_consent_records");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_consent_records_user_id");

                    b.ToTable("consent_records", (string)null);
                });

            modelBuilder.Entity("Cauce.Domain.Identity.InvitationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("code_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("NutritionistId")
                        .HasColumnType("uuid")
                        .HasColumnName("nutritionist_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid?>("UsedByPatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("used_by_patient_id");

                    b.HasKey("Id")
                        .HasName("pk_invitation_codes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_invitation_codes_code");

                    b.HasIndex("NutritionistId")
                        .HasDatabaseName("ix_invitation_codes_nutritionist_id");

                    b.HasIndex("UsedByPatientId")
                        .HasDatabaseName("ix_invitation_codes_used_by_patient_id");

                    b.HasIndex("Status", "ExpiresAt")
                        .HasDatabaseName("ix_invitation_codes_status_expires_at");

                    b.ToTable("invitation_codes", (string)null);
                });

            modelBuilder.Entity("Cauce.Domain.Identity.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("token_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_used");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_password_reset_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_password_reset_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_password_reset_tokens_user_id");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("Cauce.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("email_verified");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("FcmToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("fcm_token");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsInActivePilot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_in_active_pilot");

                    b.Property<string>("KeycloakId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("keycloak_id");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("KeycloakId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_keycloak_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_users_status");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Cauce.Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("notification_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("channel");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("related_entity_type");

                    b.Property<short>("RetryCount")
                        .HasColumnType("smallint")
                        .HasColumnName("retry_count");

                    b.Property<DateTime>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("Status", "ScheduledFor")
                        .HasDatabaseName("ix_notifications_dispatch")
                        .HasFilter("status = 'pending'");

                    b.HasIndex("UserId", "Type", "RelatedEntityType", "RelatedEntityId")
                        .IsUnique()
                        .HasDatabaseName("ux_notifications_dedup")
                        .HasFilter("related_entity_id IS NOT NULL");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Cauce.Domain.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("outbox_message_id");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid")
                        .HasColumnName("aggregate_id");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aggregate_type");

                    b.Property<short>("Attempts")
                        .HasColumnType("smallint")
                        .HasColumnName("attempts");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_pending")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Cauce.Domain.Patients.Allergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("allergy_id");

                    b.Property<string>("AllergyType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("allergy_type");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_allergies");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_allergies_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_allergies_name");

                    b.ToTable("allergies", (string)null);
                });

            modelBuilder.Entity("Cauce.Domain.Patients.NutritionistPatient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<Guid?>("InvitationCodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitation_code_id");

                    b.Property<Guid>("NutritionistId")
                        .HasColumnType("uuid")
                        .HasColumnName("nutritionist_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UnassignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unassigned_at");

                    b.HasKey("Id")
                        .HasName("pk_nutritionist_patient");

                    b.HasIndex("InvitationCodeId")
                        .HasDatabaseName("ix_nutritionist_patient_invitation_code_id");

                    b.HasIndex("NutritionistId")
                        .HasDatabaseName("ix_nutritionist_patient_nutritionist_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_nutritionist_patient_patient_id");

                    b.HasIndex("NutritionistId", "PatientId")
                        .IsUnique()
                        .HasDatabaseName("uq_nutritionist_patient_active")
                        .HasFilter("status = 'active'");

                    b.ToTable("nutritionist_patient", (string)null);
                });

            modelBuilder.Entity("Cauce.Domain.Patients.PatientAllergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("patient_allergy_id");

                    b.Property<Guid>("AllergyId")
                        .HasColumnType("uuid")
                        .HasColumnName("allergy_id");

                    b.Property<DateTime>("DeclaredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("declared_at");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.HasKey("Id")
                        .HasName("pk_patient_allergies");

                    b.HasIndex("AllergyId")
                        .HasDatabaseName("ix_patient_allergies_allergy_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_patient_allergies_patient_id");

                    b.HasIndex("PatientId", "AllergyId")
                        .IsUnique()
                        .HasDatabaseName("uq_patient_allergy");

                    b.ToTable("patient_allergies", (string)null);
                });

            modelBuilder.Entity("Cauce.Domain.Patients.PatientProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("BiologicalSex")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("biological_sex");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<DateOnly?>("DiagnosisDate")
                        .HasColumnType("date")
                        .HasColumnName("diagnosis_date");

                    b.Property<decimal>("HeightCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("height_cm");

                    b.Property<string>("IbsSubtype")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ibs_subtype");

                    b.Property<string>("Medications")
                        .HasColumnType("text")
                        .HasColumnName("medications");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("onboarding_completed");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_patient_profiles");

                    b.HasIndex("IbsSubtype")
                        .HasDatabaseName("ix_patient_profiles_ibs_subtype");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_patient_profiles_user_id");

                    b.ToTable("patient_profiles", null, t =>
                        {
                            t.HasCheckConstraint("ck_patient_profiles_height_cm", "height_cm > 0 AND height_cm < 250");

                            t.HasCheckConstraint("ck_patient_profiles_weight_kg", "weight_kg > 0 AND weight_kg < 500");
                        });
                });

            modelBuilder.Entity("Cauce.Domain.Recommendations.ModelVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("version_id");

                    b.Property<DateTime>("DeployedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deployed_at");

                    b.Property<string>("DeployedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("deployed_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ModelHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("model_hash");

                    b.Property<string>("PerformanceMetricsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("performance_metrics");

                    b.Property<int?>("TrainingDatasetSize")
                        .HasColumnType("integer")
                        .HasColumnName("training_dataset_size");

                    b.Property<string>("VersionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("version_name");

                    b.HasKey("Id")
                        .HasName("pk_model_versions");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasDatabaseName("ix_model_versions_only_one_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("ModelHash")
                        .IsUnique()
                        .HasDatabaseName("ux_model_versions_model_hash");

                    b.HasIndex("VersionName")
                        .IsUnique()
                        .HasDatabaseName("ux_model_versions_version_name");

                    b.ToTable("model_versions", (string)null);
                });

            modelBuilder.Entity("Cauce.Domain.Recommendations.Recommendation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.Property<string>("AiExplanation")
                        .HasColumnType("text")
                        .HasColumnName("ai_explanation");

                    b.Property<bool>("AutoApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_approved");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTime?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("ExplanationSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("explanation_source");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<Guid>("ModelVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("model_version_id");

                    b.Property<string>("NutritionistNote")
                        .HasColumnType("text")
                        .HasColumnName("nutritionist_note");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedByNutritionistId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by_nutritionist_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_recommendations");

                    b.HasIndex("ModelVersionId")
                        .HasDatabaseName("ix_recommendations_model_version_id");

                    b.HasIndex("PatientId", "Status", "GeneratedAt")
                        .HasDatabaseName("ix_recommendations_patient_status_generated");

                    b.HasIndex("ReviewedByNutritionistId", "Status", "GeneratedAt")
                        .HasDatabaseName("ix_recommendations_nutritionist_pending")
                        .HasFilter("status = 'pending_review'");

                    b.ToTable("recommendations", (string)null);
                });

            modelBuilder.Entity("Cauce.Domain.Recommendations.RecommendationFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("feedback_id");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comment");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sync_status");

                    b.Property<bool>("WasApplied")
                        .HasColumnType("boolean")
                        .HasColumnName("was_applied");

                    b.HasKey("Id")
                        .HasName("pk_recommendation_feedback");

                    b.HasIndex("RecommendationId")
                        .IsUnique()
                        .HasDatabaseName("ux_recommendation_feedback_recommendation_id");

                    b.ToTable("recommendation_feedback", (string)null);
                });

            modelBuilder.Entity("Cauce.Domain.Recommendations.RecommendationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_item_id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action_type");

                    b.Property<Guid>("FoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("food_id");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text")
                        .HasColumnName("reasoning");

                    b.Property<Guid>("RecommendationId")
                        .HasColumnType("uuid")
                        .HasColumnName("recommendation_id");

                    b.Property<Guid?>("SubstituteFoodId")
                        .HasColumnType("uuid")
                        .HasColumnName("substitute_food_id");

                    b.HasKey("Id")
                        .HasName("pk_recommendation_items");

                    b.HasIndex("FoodId")
                        .HasDatabaseName("ix_recommendation_items_food_id");

                    b.HasIndex("RecommendationId")
                        .HasDatabaseName("ix_recommendation_items_recommendation_id");

                    b.HasIndex("SubstituteFoodId")
                        .HasDatabaseName("ix_recommendation_items_substitute_food_id");

                    b.ToTable("recommendation_items", (string)null);
                });

            modelBuilder.Entity("Cauce.Domain.Reports.ClinicalReportMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("clinical_report_metadata_id");

                    b.Property<int>("FileSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("file_size_bytes");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<Guid>("GeneratedByNutritionistId")
                        .HasColumnType("uuid")
                        .HasColumnName("generated_by_nutritionist_id");

                    b.Property<string>("ObjectStoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_storage_path");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.HasKey("Id")
                        .HasName("pk_clinical_reports_metadata");

                    b.HasIndex("GeneratedByNutritionistId")
                        .HasDatabaseName("ix_clinical_reports_metadata_generated_by_nutritionist_id");

                    b.HasIndex("PatientId", "GeneratedAt")
                        .HasDatabaseName("ix_clinical_reports_metadata_patient_generated");

                    b.ToTable("clinical_reports_metadata", (string)null);
                });

            modelBuilder.Entity("Cauce.Infrastructure.Persistence.Entities.UserRoleEntity", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("ux_user_roles_role_name");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Cauce.Domain.ClinicalRegistry.ClinicalNote", b =>
                {
                    b.HasOne("Cauce.Domain.ClinicalRegistry.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_clinical_notes_meals_meal_id");

                    b.HasOne("Cauce.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clinical_notes_users_patient_id");

                    b.HasOne("Cauce.Domain.ClinicalRegistry.Symptom", null)
                        .WithMany()
                        .HasForeignKey("SymptomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_clinical_notes_symptoms_symptom_id");
                });

            modelBuilder.Entity("Cauce.Domain.ClinicalRegistry.CustomFood", b =>
                {
                    b.HasOne("Cauce.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_foods_users_patient_id");
                });

            modelBuilder.Entity("Cauce.Domain.ClinicalRegistry.CustomFoodIngredient", b =>
                {
                    b.HasOne("Cauce.Domain.ClinicalRegistry.CustomFood", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("CustomFoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_custom_food_ingredients_custom_foods_custom_food_id");

                    b.HasOne("Cauce.Domain.ClinicalRegistry.FoodItem", null)
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_custom_food_ingredients_food_items_food_id");
                });

            modelBuilder.Entity("Cauce.Domain.ClinicalRegistry.IbsSssAssessment", b =>
                {
                    b.HasOne("Cauce.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ibs_sss_assessments_users_patient_id");
                });

            modelBuilder.Entity("Cauce.Domain.ClinicalRegistry.Meal", b =>
                {
                    b.HasOne("Cauce.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meals_users_patient_id");
                });

            modelBuilder.Entity("Cauce.Domain.ClinicalRegistry.MealItem", b =>
                {
                    b.HasOne("Cauce.Domain.ClinicalRegistry.CustomFood", null)
                        .WithMany()
                        .HasForeignKey("CustomFoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_meal_items_custom_foods_custom_food_id");

                    b.HasOne("Cauce.Domain.ClinicalRegistry.FoodItem", null)
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_meal_items_food_items_food_id");

                    b.HasOne("Cauce.Domain.ClinicalRegistry.Meal", null)
                        .WithMany("Items")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meal_items_meals_meal_id");
                });

            modelBuilder.Entity("Cauce.Domain.ClinicalRegistry.Symptom", b =>
                {
                    b.HasOne("Cauce.Domain.ClinicalRegistry.Meal", null)
                        .WithMany()
                        .HasForeignKey("AssociatedMealId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_symptoms_meals_associated_meal_id");

                    b.HasOne("Cauce.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_symptoms_users_patient_id");
                });

            modelBuilder.Entity("Cauce.Domain.Identity.ConsentRecord", b =>
                {
                    b.HasOne("Cauce.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_consent_records_users_user_id");
                });

            modelBuilder.Entity("Cauce.Domain.Identity.InvitationCode", b =>
                {
                    b.HasOne("Cauce.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("NutritionistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invitation_codes_users_nutritionist_id");

                    b.HasOne("Cauce.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UsedByPatientId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_invitation_codes_users_used_by_patient_id");
                });

            modelBuilder.Entity("Cauce.Domain.Identity.PasswordResetToken", b =>
                {
                    b.HasOne("Cauce.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_password_reset_tokens_users_user_id");
                });

            modelBuilder.Entity("Cauce.Domain.Identity.User", b =>
                {
                    b.HasOne("Cauce.Infrastructure.Persistence.Entities.UserRoleEntity", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_user_roles_role_id");
                });

            modelBuilder.Entity("Cauce.Domain.Notifications.Notification", b =>
                {
                    b.HasOne("Cauce.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");
                });

            modelBuilder.Entity("Cauce.Domain.Patients.NutritionistPatient", b =>
                {
                    b.HasOne("Cauce.Domain.Identity.InvitationCode", null)
                        .WithMany()
                        .HasForeignKey("InvitationCodeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_nutritionist_patient_invitation_codes_invitation_code_id");

                    b.HasOne("Cauce.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("NutritionistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_nutritionist_patient_users_nutritionist_id");

                    b.HasOne("Cauce.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_nutritionist_patient_users_patient_id");
                });

            modelBuilder.Entity("Cauce.Domain.Patients.PatientAllergy", b =>
                {
                    b.HasOne("Cauce.Domain.Patients.Allergy", null)
                        .WithMany()
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patient_allergies_allergies_allergy_id");

                    b.HasOne("Cauce.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_allergies_users_patient_id");
                });

            modelBuilder.Entity("Cauce.Domain.Patients.PatientProfile", b =>
                {
                    b.HasOne("Cauce.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_patient_profiles_users_user_id");
                });

            modelBuilder.Entity("Cauce.Domain.Recommendations.Recommendation", b =>
                {
                    b.HasOne("Cauce.Domain.Recommendations.ModelVersion", null)
                        .WithMany()
                        .HasForeignKey("ModelVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recommendations_model_versions_model_version_id");

                    b.HasOne("Cauce.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommendations_users_patient_id");

                    b.HasOne("Cauce.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ReviewedByNutritionistId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recommendations_users_reviewed_by_nutritionist_id");
                });

            modelBuilder.Entity("Cauce.Domain.Recommendations.RecommendationFeedback", b =>
                {
                    b.HasOne("Cauce.Domain.Recommendations.Recommendation", null)
                        .WithOne("Feedback")
                        .HasForeignKey("Cauce.Domain.Recommendations.RecommendationFeedback", "RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommendation_feedback_recommendations_recommendation_id");
                });

            modelBuilder.Entity("Cauce.Domain.Recommendations.RecommendationItem", b =>
                {
                    b.HasOne("Cauce.Domain.ClinicalRegistry.FoodItem", null)
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_recommendation_items_food_items_food_id");

                    b.HasOne("Cauce.Domain.Recommendations.Recommendation", null)
                        .WithMany("Items")
                        .HasForeignKey("RecommendationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recommendation_items_recommendations_recommendation_id");

                    b.HasOne("Cauce.Domain.ClinicalRegistry.FoodItem", null)
                        .WithMany()
                        .HasForeignKey("SubstituteFoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_recommendation_items_food_items_substitute_food_id");
                });

            modelBuilder.Entity("Cauce.Domain.Reports.ClinicalReportMetadata", b =>
                {
                    b.HasOne("Cauce.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("GeneratedByNutritionistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_clinical_reports_metadata_users_generated_by_nutritionist_id");

                    b.HasOne("Cauce.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_clinical_reports_metadata_users_patient_id");
                });

            modelBuilder.Entity("Cauce.Domain.ClinicalRegistry.CustomFood", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("Cauce.Domain.ClinicalRegistry.Meal", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Cauce.Domain.Recommendations.Recommendation", b =>
                {
                    b.Navigation("Feedback");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
