<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cauce.Application\Cauce.Application.csproj" />
    <ProjectReference Include="..\Cauce.Domain\Cauce.Domain.csproj" />
    <ProjectReference Include="..\Cauce.Infrastructure\Cauce.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.*" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.*" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.*" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.*" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.*" />
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.*" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.*" />
  </ItemGroup>

</Project>
